auction/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('products/',include('product.urls')),
    path('user/',include('userauth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from . import views
from .views import custom_404_view

app_name = 'core'

urlpatterns = [
    # Home Page
    path('',views.index,name='index'),

    # Terms & Condition Page
    path('terms',views.terms, name='terms'),

    # Vendor List Page
    path('vendors/',views.vendor_list_view, name='vendor-list'),
    path('vendor-detail/<int:pk>/',views.vendor_detail, name='vendor-detail'),

    # Tags Page
    path('products/tag/<slug:tag_slug>/',views.tag_list, name='tags'),
    
    # add to cart
    path('add-to-cart/', views.add_to_cart, name="add-to-cart"),

    # cart list page
    path('cart-list/', views.cart_view, name="cart-list"),

    # delete product from cart
    path('delete-from-cart/', views.delete_from_cart, name="delete-from-cart"),

    # update product price from cart
    path('update-cart/', views.update_cart, name="update-cart"),

    # user profile pages
    path('dashboard/', views.customer_dashboard, name="dashboard"),
    path('user/profile/', views.user_profile, name="profile"),
    path('user/edit/', views.profile_edit, name="profile-edit"),
    
    # contact
    path('contact/', views.contact, name="contact"),
    path('ajax-contact-form/', views.ajax_contact , name="ajax-contact-form"),

]

handler404 = custom_404_view

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    #for bid prediction
    path('predict_bid/',views.predict_bid_price,name="predict_bid"),

    path('auction-category-list/', views.category_list, name='category'),
    path('product-category-list/', views.category_list_p, name='category-p'),

    path('product-list/<int:pk>', views.product_list_view, name='product-list'),
    path('auction-list/<int:pk>', views.auction_list_view, name='auction-list'),

    path('<int:pk>/', views.product_detail, name='detail'),
    path('auction/<int:pk>/', views.auction_detail, name='auction_detail'),

    path('bidlist', views.bids, name='bids'),
    
    # new product and auction
    path('create_product/', views.new, name='new'),
    path('create_auction/', views.new_auction, name='new_auction'),

    # shop page
    path('shop/',views.shop_view,name='shop'),

    # bid list page
    path('bid/',views.bid_view,name='bid'),

    # add review
    path('add_review/<int:pk>', views.add_review, name='add_review'),

    # search
    path('search',views.search_view,name='search'),

    # checkout
    path('checkout',views.checkout_view,name='checkout'),

    # after payment
    path('payment-completed', views.payment_completed, 
         name = 'payment-completed'),
]

userauth/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from django.conf import settings
# from django.conf.urls.static import static

from .forms import LogInForm

app_name = 'userauth'

urlpatterns = [
    path('',views.home),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login_view, name='login'),
    path('logout',views.logout_view,name='logout')
]

product/forms.py
from django import forms

from .models import Product, Auction

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['category', 'title', 'description', 'price', 'image','tags']
        labels = {
            'category': 'Category',
            'title': 'Title',
            'description': 'Description',
            'price': 'Price',
            'image': 'Image',
            'tags': 'Tags',
        }
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'title': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': 'w-full py-4 pr-6 rounded-xl'
            }),
            'tags': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
        }


class NewAuctionForm(forms.ModelForm):
    class Meta:
        model = Auction
        fields = ['categori', 'name', 'description', 'bid', 'image','duration','tags']
        labels = {
            'categori': 'Category',
            'name': 'Name',
            'description': 'Description',
            'bid': 'Opening Bid',
            'image': 'Image',
            'duration': 'Duration',
            'tags': 'Tags',
        }
        widgets = {
            'categori': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'bid': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': 'w-full py-4 pr-6 rounded-xl'
            }),
            'duration': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'tags': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

product/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Avg
from django.urls import reverse
from django.contrib import messages
from .models import Product, Auction, ProductReview, Vendor, Auctioneer, Category, Bids, Winner
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .forms import NewProductForm, NewAuctionForm
from core.forms import ProductReviewForm
from django.db.models import Q
import json
from .utils import predict_price 


# Create your views here.
def category_list(request):
    categories = Category.objects.all()

    return render(request, 'product/category-list.html', {
        "categories": categories,
    })


def category_list_p(request):
    categories = Category.objects.all()

    return render(request, 'product/category-list-p.html', {
        "categories": categories,
    })


def auction_list_view(request, pk):
    category = Category.objects.get(pk=pk)
    auction = Auction.objects.filter(live=True, categori=category)
    
    return render(request, 'product/auction-list.html', {
        'category': category,
        'auction': auction,
    })


def product_list_view(request, pk):
    category = Category.objects.get(pk=pk)
    product = Product.objects.filter(on_stock=True, category=category)
    
    return render(request, 'product/product-list.html', {
        'category': category,
        'product': product,
    })



def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    related_products = Product.objects.filter(category=product.category, is_sold=False).exclude(pk=pk)[0:4]

    vendors = Vendor.objects.all()

    #this means this product should be equal to ProductReview product field
    reviews = ProductReview.objects.filter(product=product).order_by("-date") 

    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

    #product review form
    review_form = ProductReviewForm()
    make_review = True

    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()

        if user_review_count > 0:
            make_review = False

    return render(request, 'product/detail.html', {
        'p': product,
        'average_rating': average_rating,
        'reviews': reviews,
        'vendors': vendors,
        'make_review': make_review,
        'review_form': review_form,
        'related_products': related_products,
    })



# this function returns minimum bid required to place a user's bid
def minbid(min_bid, present_bid):
    for bids_list in present_bid:
        if min_bid < int(bids_list.bid):
            min_bid = int(bids_list.bid)
    return min_bid



def predict_bid_price(request):
    if request.method == 'POST':
        print(request.POST)
        bid = request.POST.get('bid')
        bidtime = request.POST.get('bid_time')
        openbid = request.POST.get('open_bid')
        item = request.POST.get('item')
        auction_type = request.POST.get('auction_type')
    perdections = [11]
    perdections = predict_price({
        'bid':bid,
        'bidtime':bidtime,
        'openbid':openbid,
        'item':item,
        'auction_type':auction_type    }
    )
    return JsonResponse({
        'price':perdections[0]
    },safe=False)



def auction_detail(request, pk):
    predicted_price = None

    if request.method == 'POST':
        print(request.POST)
        bid = request.POST.get('bid')
        bidtime = request.POST.get('bid_time')
        openbid = request.POST.get('open_bid')
        item = request.POST.get('item')
        auction_type = request.POST.get('auction_type')
        
        perdictions = predict_price({
        'bid':bid,
        'bidtime':bidtime,
        'openbid':openbid,
        'item':item,
        'auction_type':auction_type    }
        )
        predicted_price = perdictions[0]

    auction = get_object_or_404(Auction, pk=pk)
    related_auctions = Auction.objects.filter(categori=auction.categori,live=True).exclude(pk=pk)[0:4]

    biddesc = Auction.objects.get(pk = pk, live = True)
    bids_present = Bids.objects.filter(listingid = pk)

    max_bid = minbid(biddesc.bid, bids_present)

    # auction.auction is used to access the related BidT object through the one-to-one relationship.
    bid_time= auction.auction
    end_time = bid_time.end_time if bid_time else None

    # In auction_detail view
    half_duration = auction.duration/2

    try:
        winner_objects = Bids.objects.filter(bid=max_bid)  
        # Retrieve queryset of winner objects
        if winner_objects.exists():  
            # Check if there are any winner objects
            winner_object = winner_objects.first()  # Retrieve the first winner object from the queryset
            winner_name = winner_object.user
        else:
        # Handle the case where there are no winners
            winner_name = None
    
    except:
        winner_name = None


    return render(request, 'product/auction_detail.html', {
        'auction': auction,
        'related_auctions': related_auctions,
        'endingtime': end_time,
        "current_bid": minbid(biddesc.bid, bids_present),
        'winner_name': winner_name,
        'predicted_price': predicted_price,
        'half_duration': half_duration,
    })



def determine_winner(auct_id):
    try:
        # Get the user with the highest bid for the given listing
        winner_object = Bids.objects.filter(listingid=auct_id).order_by('-bid').first()
        winner_name = winner_object.user.username if winner_object else None
        return winner_name
    except Bids.DoesNotExist:
        return None


@login_required
def bids(request):
    bid_amnt = request.GET["bid_amnt"]
    try:
        auct_id = int(request.GET["auct_d"])
    except (KeyError, ValueError):
        return HttpResponse("Invalid or missing listing ID")


    bids_present = Bids.objects.filter(listingid = auct_id)
    startingbid = Auction.objects.get(pk = auct_id)
    min_req_bid = startingbid.bid
    min_req_bid = minbid(min_req_bid, bids_present)
    
    if int(bid_amnt) > int(min_req_bid):
        mybid = Bids(user = request.user, listingid = auct_id , bid = bid_amnt)
        mybid.save()

        winner_name = determine_winner(auct_id)

        messages.success(request, f"Congratulations, {request.user}! Your bid has been successfully placed. 🎉 Thank you for participating in the auction.")

        # storing the winner's name in the session
        request.session['winner_name'] = winner_name

        redirect_url = reverse('product:auction_detail', args=[auct_id])
    
        return redirect(redirect_url)
    else:
        messages.warning(request, f"Sorry, {request.user} ! Your bid should be higher than ${min_req_bid}.")

        return redirect(reverse('product:auction_detail', args=[auct_id]))
    
    return auction_detail(request, auct_id)



@login_required
def new(request):
    vendor_instance, created = Vendor.objects.get_or_create(user=request.user)
    if request.method == 'POST':
        form = NewProductForm(request.POST, request.FILES)

        if form.is_valid():
            product = form.save(commit=False)
            product.vendor = vendor_instance
            product.save()

            return redirect('product:detail', pk=product.id)
        else:
            print(form.errors)
    else:
        form = NewProductForm()

    return render(request, 'product/new.html', {
        'form': form,
        'title': 'New product',
    })



@login_required
def new_auction(request):
    auctioneer_instance, created = Auctioneer.objects.get_or_create(user=request.user)
    if request.method == 'POST':
        form = NewAuctionForm(request.POST, request.FILES)

        if form.is_valid():
            auction = form.save(commit=False)
            auction.auctioneer = auctioneer_instance
            auction.save()

            return redirect('product:auction_detail', pk=auction.id)
        else:
            print(form.errors)
    else:
        form = NewAuctionForm()

    return render(request, 'product/new_auction.html', {
        'form': form,
        'title': 'New auction',
    })



def shop_view(request):
    categories = Category.objects.all()
    products = Product.objects.filter(is_sold=False).order_by("-date")
    vendors = Vendor.objects.all()

    vendor_id = request.GET.get('vendor', 0)
    category_id = request.GET.get('category', 0)
    
    if vendor_id:
        products = products.filter(vendor_id=vendor_id)

    if category_id:
        products = products.filter(category_id=category_id)


    return render(request, 'product/shop.html',{
        'categories': categories,
        'products': products,
        'vendors': vendors,
        'category_id': int(category_id),
        'vendor_id': int(vendor_id),
    })



# this is for auction list page
def bid_view(request):
    categories = Category.objects.all()
    auctions = Auction.objects.filter(live=True).order_by("-date")
    auctioneers = Auctioneer.objects.all()

    auctioneer_id = request.GET.get('auctioneer', 0)
    category_id = request.GET.get('c', 0) # this c is what is used in loop in html
    
    if auctioneer_id:
        auctions = auctions.filter(auctioneer_id=auctioneer_id)

    if category_id:
        # this categori_id is generated by django as we created categori field in Auction class and django generated 'categori_id' because categori field is foreign key
        auctions = auctions.filter(categori_id=category_id)

    return render(request, 'product/bid.html',{
        'categories': categories,
        'auctions': auctions,
        'auctioneers': auctioneers,
        'category_id': int(category_id),
        'auctioneer_id': int(auctioneer_id),
    })



#this is form review form
def add_review(request,pk):

templates/product/auction-list.html
{% extends 'base.html' %}
{% block title %}{{category}} list |{% endblock %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
<div class="m-5">
    <h1 class="text-2xl font-semibold text-center mb-3">{{category}} list</h1>
    <p class="text-center mb-10">We found <span class="text-emerald-500">{{auction.count}}</span> {{category}} for you.</p>


    <div class="container gap-2" id="p-section">
        {% for a in auction %}
        <div class="card">
            <a href="{% url 'product:auction_detail' a.id %}" class="detail">
                <div>
                    <img src="{{ a.image.url }}" class="rounded-t-xl border-1" id="product">
                    <span class="ml-2 bg-rose-600 text-white py-1 px-3 rounded-md" id="auction-live"><i class="far fa-dot-circle"> Live</i></span>
                </div>
                
                <div class="p-6 border-t-2 bg-white w-70 card1">
                    <h3 class="text-xl text-center font-medium mb-2">{{ a.name }}</h3>
                    <div class="flex">
                        <strong class="text-gray-900">Opening Bid:</strong>
                        <p class="text-gray-700 text-center ml-2"><span id="price">$</span>{{ a.bid }}</p>
                        <div class="go-arrow">
                            →
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

templates/product/category-list-p.html
{% extends 'base.html' %}
{% block title %}Categories |{% endblock %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
<div>
    <div class="mt-8 mb-10 ">
        <h2 class="text-4xl text-[#253D4E] font-bold text-center mb-4">Categories</h2>
        <h3 class="text-center"><a href="{% url 'core:index' %}" class="text-gray-500 hover:text-orange-500"><i id="home" class="fa fa-home text-xs"></i> Home </a>/ Categories / Product Categories</h3>
    </div>

    <p class="text-center mb-5 text-xl">There are <span class="text-emerald-500">{{categories.count}}</span> Categories for Auction</p>

    <div class="grid grid-cols-4 gap-3 category-container px-10">
        {% for c in categories %}
            <div class="category-card">
                <a href="{% url 'product:product-list' c.id %}" class="detail">
                    <div>
                        <img src="{{ c.image.url }}" class="rounded-t-xl border-1">
                    </div>
                    <h3 class="text-xl text-center font-semibold">{{ c.name }}</h3>
                    <p class="text-center"><span class="text-emerald-500">{{ c.products.count }}</span> Auctions</p>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/product/category-list.html
{% extends 'base.html' %}
{% block title %}Categories |{% endblock %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
<div>
    <div class="mt-8 mb-10 ">
        <h2 class="text-4xl text-[#253D4E] font-bold text-center mb-4">Categories</h2>
        <h3 class="text-center"><a href="{% url 'core:index' %}" class="text-gray-500 hover:text-orange-500"><i id="home" class="fa fa-home text-xs"></i> Home </a>/ Categories / Auction Categories</h3>
    </div>

    <p class="text-center mb-5 text-xl">There are <span class="text-emerald-500">{{categories.count}}</span> Categories for Auction</p>

    <div class="grid grid-cols-4 gap-3 category-container px-10">
        {% for c in categories %}
            <div class="category-card">
                <a href="{% url 'product:auction-list' c.id %}" class="detail">
                    <div>
                        <img src="{{ c.image.url }}" class="rounded-t-xl border-1">
                    </div>
                    <h3 class="text-xl text-center font-semibold">{{ c.name }}</h3>
                    <p class="text-center"><span class="text-emerald-500">{{ c.auctions.count }}</span> Auctions</p>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/product/detail.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}

{% block title %}{{ product.title }}{% endblock %}

{% block content %}
<!-- main detail section -->
<link rel="stylesheet" href="{% static 'css/detail.css' %}" />

<div class="flex mt-4 justify-evenly">
    <div class="mr-2">
        <img src="{{ p.image.url }}" class="rounded-md ml-4" id="det-image" style="height: 380px; width: 400px; object-fit: contain;">
    </div>

    <div class="col-span-2 p-6 rounded-xl mr-3 pdetail">
        <h1 class="mb-2 text-3xl font-medium text-[#ee6846]">{{ p.title }}</h1>
        <div class="mb-3">
            {% if average_rating.rating %}
                {% for _ in average_rating.rating|int_range %}
                    <i class="fas fa-star text-warning" style="color: #FFB534;"></i>
                {% endfor %}
                ({{ average_rating.rating|floatformat }})
            {% endif %}


        </div>
        <hr>
        <div class="flex">
            <span class="mt-3 text-3xl font-medium text-[#0f2e40]">$</span><p class="mt-3 text-3xl mr-5 font-medium current-price current-price-{{ p.id }} text-[#0f2e40]">{{ p.price }}</p>
            <s class="text-xl font-medium text-gray-400 relative -bottom-4">${{ p.old_price }}</s>
        </div>
        <p class="text-gray-500 mt-1 "><strong>Vendor: </strong><span class="text-emerald-600">{{ p.vendor }}</span></p>
        <p class="text-gray-500 mt-1 mb-2"><strong>Tags:</strong>
            {% for tag in p.tags.all %}
                <a href="{% url 'core:tags' tag.slug %}" class="text-emerald-600">
                    #{{ tag.name }},
                </a>
            {% endfor %}
        </p>
        <hr>
        <div class="mt-8">
            <div class=" p-2 h-3/4 rounded-lg text-center">
                <div class="text-center" id="home-cart">
                    <input type="number" value="1" class="bg-gray-100 mb-4 p-3 w-14 rounded-md border-2 border-[#ee6846] product-quantity-{{ p.id }}" name="" id="product-quantity">

                    <input type="hidden" value="{{ p.id }}" class="product-pid-{{ p.id }}">

                    <input type="hidden" value="{{ p.image.url }}"
                    class="product-image-{{ p.id }}">

                    <input type="hidden" value="{{ p.id }}" class="product-id-{{ p.id }}">

                    <input type="hidden" value="{{ p.title }}" class="product-title-{{ p.id }}">
                </div>

                <button type="submit" id="add-to-cart-btn" class="add add-to-cart-btn bg-[#ee6846] px-6 py-2 rounded-md text-xl text-white font-medium hover:bg-[#ee5840] text-center" data-index="{{ p.id }}"><i class="fa-regular fa-cart-shopping" ></i> &nbsp;Add to Cart</button>
            </div>
        </div>
        
    </div>

    <div class="product-pay">
        <div class="bg-gray-100 rounded-xl p-4 mr-4">
            {% if request.user == p.created_by %}
                <div class="p-3 text-center bg-white rounded-xl">
                    <p>This is your Product.</p>
                    <a href="#" class="inline-block mt-6 px-5 py-2 font-medium bg-emerald-500 text-white rounded-md hover:bg-emerald-500 mr-4">Edit</a><br>
                    <a href="#" class="inline-block mt-3 px-5 py-2 font-medium bg-rose-600 text-white rounded-md hover:bg-rose-700">Delete</a>
                </div>
            {% else %}  
            <div>
                <div class="w-full mb-2 p-2 h-3/4 rounded-lg text-center">
                    <p class="mb-1 text-[#0f2e40] font-semibold text-2xl">Vendor</p>
                </div>
                <div class="flex align-middle mb-4 justify-center">
                    <img src="{{ p.vendor.image.url }}" alt="image" style="height: 70px; width: 70px; object-fit: cover;" class="rounded-full mr-4">
                    <a href="{% url 'core:vendor-detail' p.vendor.id %}" class="font-semibold flex justify-center items-center text-xl text-[#ee6846]">
                        {{ p.vendor }}
                    </a>
                </div>
                <hr class="mb-3">
                <div class="mb-1 flex items-center justify-center">
                    <i class="fa-solid fa-location-dot text-[#ee6846]"></i> &nbsp;<span class="font-medium mr-1">Address:</span> <span class="ml-1">{{ p.vendor.address }}</span>
                </div>
                <div class="flex items-center justify-center">
                    <i class="fa-solid fa-headphones text-[#ee6846]"></i> &nbsp;<span class="font-medium mr-1">Contact:</span> <span class="ml-1">{{ p.vendor.contact }}</span>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>

<div class="mt-8 bg-gray-100 py-4 px-8">
    <strong class="text-gray-500 text-xl">Description:</strong>
    {% if p.description %}
    <p class="text-gray-700 mt-2">
        {{ p.description }}
    </p>
    {% endif %}
</div>
<!----------------------------------------------------------------->
<!-------------------------- reviews section ---------------------->
<!----------------------------------------------------------------->

<div class="mt-8 bg-gray-100 p-4">
    <h2 class="mt-8 text-2xl font-medium">Reviews ({{ reviews.count }})</h2>
    <div class="flex mt-1 mb-3 justify-evenly">
        <div style="min-width: 50rem;" class="comment">
            {% for r in reviews %}
            <div class="mt-3 bg-white p-4 rounded-xl">
                <img src="https://cvhrma.org/wp-content/uploads/2015/07/default-profile-photo.jpg" alt="profile" style="max-width: 3.125rem;" class="rounded-full">
                <div class="flex">
                    <h2 class="text-left mr-6 text-emerald-500 underline">{{ r.user.username }}</h2>
                    <span class="text-gray-400">{{ r.date|date:"d M, Y" }}</span>
                </div>
                <div>
                    {% for s in r.rating|ljust:r.rating %}
                        <i class="fas fa-star text-warning" style="color: #FFB534;"></i>
                    {% endfor %}
                </div>
                <p>{{ r.review }}</p>
            </div>
            {% endfor %}

            <!-- this will make a user review only one time -->
            {% if make_review == True %}
            <div class="mt-10">
                <h3 class="mt-3 text-xl font-medium hide_form">Add a review</h3>
                <span class="font-medium text-emerald-500" id="review"></span>
                <form action="{% url 'product:add_review' p.id %}" id="commentForm" method="POST" class="hide_form">
                    {% csrf_token %}
                    <div class="mt-3">
                        {{ review_form.review }}
                    </div>
                    <h4 class="mt-3 mb-2 text-xl font-medium">Rating:</h4>
                    <div>
                        {{ review_form.rating }}
                    </div>
                    {% if request.user.is_authenticated %}
                    <div class="mt-5">
                        <button class="p-3 font-semibold rounded-md border border-[#ee6846] hover:text-white hover:bg-[#ee6846] text-[#ee6846]" type="submit">Submit review</button>
                    </div>
                    {% else %}
                        <p class="mt-5">Please <a href="{% url 'userauth:login' %}" class="text-emerald-500 hover:text-emerald-600">login</a> to add review.</p>
                    {% endif %} 
                </form>
            </div>
            {% endif %}
        </div>
        
        <div>
            <div class="bg-white ml-4 mt-3 p-4 rounded-xl" style="min-width: 24.063rem; max-height: 31.25rem;">
                <h2 class="text-xl font-medium mt-4">Customer Reviews</h2>
                <div>
                    <h3 class="mt-4 text-center mb-4"><span class="text-emerald-500">{{ average_rating.rating|floatformat }}</span> out of 5.0</h3>
                </div>
            </div>
        </div>
    </div>
</div>



<!------------------------------------------------------------------->
<!--------------------- similar products section ------------------->
<!------------------------------------------------------------------>
<div class="mt-4 px-6 py-5 mb-4">
    <h2 class="mb-12 text-2xl text-center font-semibold">Similar products</h2>

    <div class="container gap-2" id="p-section">
        {% for p in related_products %}
            <div class="card">
                <div class="detail">
                    <div>
                        <img src="{{ p.image.url }}" class="rounded-t-xl border-1" id="product">
                        <!-- we are making all hidden input so that function.js can take the value of the product and add to cart from homepage -->
                        <div class="text-center" id="home-cart">
                            <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{ p.id }}">

                            <input type="hidden" value="{{ p.id }}" class="product-pid-{{ p.id }}">

                            <input type="hidden" value="{{ p.image.url }}"
                            class="product-image-{{ p.id }}">

                            <input type="hidden" value="{{ p.id }}" class="product-id-{{ p.id }}">

                            <input type="hidden" value="{{ p.title }}" class="product-title-{{ p.id }}">

                            <button class="add add-to-cart-btn bg-yellow-400 text-white py-.5 px-3 hover:bg-yellow-600" id="add-to-cart-btn" data-index="{{ p.id }}"><i class="fa-regular fa-cart-shopping" ></i></button>
                        </div>
                    </div>

                    <a href="{% url 'product:detail' p.id %}" class="px-5 pt-3 border-t-2 bg-white w-70 card1">
                        <h3 class="text-xl font-medium text-center mb-2">{{ p.title }}</h3>
                        <p class="text-gray-800 font-semibold text-center text-xl"><span id="price">$</span><span class="current-price-{{ p.id }}">{{ p.price }}</span><s class="ml-2 text-sm text-gray-400">${{ p.old_price }}</s></p>
                        <div class="go-arrow">
                            →
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/product/new.html
{% extends 'base.html' %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
  <h1 class="mb-6 text-3xl text-[#0f2e40] text-center font-semibold">Add a product</h1>
  {{request.user}}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
  
    <div class="space-y-4">
      {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
      <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
          {{ field.errors }}
        {% endfor %}

        {{ form.non_field_errors }}
      </div>
    {% endif %}

    <button class="py-2 mt-4 w-full text-lg bg-indigo-950 hover:bg-indigo-900 rounded-md text-white">Submit</button>
  </form>

</div>
{% endblock %}