auction/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('products/',include('product.urls')),
    path('user/',include('userauth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from . import views
from .views import custom_404_view

app_name = 'core'

urlpatterns = [
    # Home Page
    path('',views.index,name='index'),

    # Terms & Condition Page
    path('terms',views.terms, name='terms'),

    # Vendor List Page
    path('vendors/',views.vendor_list_view, name='vendor-list'),
    path('vendor-detail/<int:pk>/',views.vendor_detail, name='vendor-detail'),

    # Tags Page
    path('products/tag/<slug:tag_slug>/',views.tag_list, name='tags'),
    
    # add to cart
    path('add-to-cart/', views.add_to_cart, name="add-to-cart"),

    # cart list page
    path('cart-list/', views.cart_view, name="cart-list"),

    # delete product from cart
    path('delete-from-cart/', views.delete_from_cart, name="delete-from-cart"),

    # update product price from cart
    path('update-cart/', views.update_cart, name="update-cart"),

    # user profile pages
    path('dashboard/', views.customer_dashboard, name="dashboard"),
    path('user/profile/', views.user_profile, name="profile"),
    path('user/edit/', views.profile_edit, name="profile-edit"),
    
    # contact
    path('contact/', views.contact, name="contact"),
    path('ajax-contact-form/', views.ajax_contact , name="ajax-contact-form"),

]

handler404 = custom_404_view

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    #for bid prediction
    path('predict_bid/',views.predict_bid_price,name="predict_bid"),

    path('auction-category-list/', views.category_list, name='category'),
    path('product-category-list/', views.category_list_p, name='category-p'),

    path('product-list/<int:pk>', views.product_list_view, name='product-list'),
    path('auction-list/<int:pk>', views.auction_list_view, name='auction-list'),

    path('<int:pk>/', views.product_detail, name='detail'),
    path('auction/<int:pk>/', views.auction_detail, name='auction_detail'),

    path('bidlist', views.bids, name='bids'),
    
    # new product and auction
    path('create_product/', views.new, name='new'),
    path('create_auction/', views.new_auction, name='new_auction'),

    # shop page
    path('shop/',views.shop_view,name='shop'),

    # bid list page
    path('bid/',views.bid_view,name='bid'),

    # add review
    path('add_review/<int:pk>', views.add_review, name='add_review'),

    # search
    path('search',views.search_view,name='search'),

    # checkout
    path('checkout',views.checkout_view,name='checkout'),

    # after payment
    path('payment-completed', views.payment_completed, 
         name = 'payment-completed'),
]

userauth/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from django.conf import settings
# from django.conf.urls.static import static

from .forms import LogInForm

app_name = 'userauth'

urlpatterns = [
    path('',views.home),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login_view, name='login'),
    path('logout',views.logout_view,name='logout')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <script src="{% static 'js/node_modules/jquery/dist/jquery.min.js' %}" defer></script>
    <script src="{% static 'js/function7.js' %}" defer></script>

    <title>{% block title %} {% endblock %} Online Auction</title>
    <script src="https://cdn.tailwindcss.com" defer></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/tw-output.css' %}" />


    <link rel="icon" href="{% static 'auction1.png' %}" type="image/x-icon">

</head>

<body style="font-family: 'Quicksand', sans-serif;">
    <div id="preloader">
    </div>

    <div class="flex pt-5 pb-4 justify-around">
        <a href="/" class="py-3 px-4 text-2xl font-bold text-[#0f2e40]"><span class="text-[#ee6846]">AU</span>CTION</a>
        <form action="{% url 'product:search' %}" method="GET get" name="search">   
            <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only">Search</label>
            <div class="relative mx-12" id="search-bar">
                <!-- the name attribute in input tag should be same as query field used variable -->
                <input type="text" value="{{ query }}" id="default-search" class="block p-4 ps-6 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50" placeholder="Search Category, Products..." style="min-width: 400px;" name="query" required>
                <button type="submit" class="absolute end-2.5 bottom-2.5 bg-[#ee6846] hover:bg-[#ee5836] font-medium rounded-lg text-white text-sm px-4 py-2">Search</button>
            </div>
        </form>
        <div>
            <a href="{% url 'core:cart-list' %}" class="flex py-3 px-4 text-xl font-medium hover:text-[#ee6846] text-gray-500"><img src="https://nest.apexcode.info/static/assets/imgs/theme/icons/icon-cart.svg" class="mr-1 text-[#0f2e40]" alt="">Cart<span id="cart-number" class="cart-items-count text-sm antialiased text-white bg-[#ee6846] px-2.5 py-1">{{ request.session.cart_data_obj|length }}</span></a>
        </div>
    </div>

    <!-- navigation bar -->
    <nav class="bg-[#0f2e40] text-gray-100 py-4 flex justify-between items-center border-y border-gray-200 shadow-lg">
    
        <div class="space-x-6 flex">
            <a href="/" class="text-lg font-semibold hover:text-[#ee6846]">Home</a>
            <div class="dropdown">
                <span class="dropbtn text-lg font-semibold">Category</span>
                <div class="dropdown-content">
                    <div class="dropdown">
                        <a href="{% url 'product:category' %}">Auction</a><hr>
                        <a href="{% url 'product:category-p' %}">Product</a>
                        <hr>
                    </div>
                </div>
            </div>
            <a href="{% url 'product:shop' %}" class="text-lg font-semibold hover:text-[#ee6846]">Shop</a>
            <a href="{% url 'product:bid' %}" class="text-lg font-semibold hover:text-[#ee6846]">Bid</a>
            <a href="{% url 'core:vendor-list' %}" class="text-lg font-semibold hover:text-[#ee6846]">Vendors</a>
            <a href="#about" class="text-lg font-semibold hover:text-[#ee6846]">About</a>
        </div>
        

        {% if request.user.is_authenticated %}
            <div class="dropdown">
                <span class="dropbtn text-lg font-semibold">&nbsp;<i class="fas fa-user"></i> &nbsp;{{ request.user.username }}</span>
                <div class="dropdown-content">
                    <a href="{% url 'core:profile' %}"><i class="fas fa-user"></i> &nbsp;Profile</a>
                    <hr>
                    <a href="{% url 'core:dashboard' %}"><i class="fa-solid fa-layer-group"></i> &nbsp;Dashboard</a>
                    <hr>
                    <!-- showing different options based on user type -->
                    {% if request.user.is_authenticated %} 
                    <div class="dropdown">
                            {% if request.user.profile.is_vendor %}
                                <a href="{% url 'product:new' %}"><i class="fa-solid fa-plus"></i> &nbsp; Add Product</a>
                            {% endif %}
                                
                            {% if request.user.profile.is_auctioneer %}
                                <a href="{% url 'product:new_auction' %}"><i class="fa-solid fa-plus"></i> &nbsp;Add Auction</a>
                            {% endif %}
                        </div>
                        <hr>
                    {% endif %}
                    <a href="{% url 'userauth:logout' %}"><i class="fa-solid fa-arrow-right-from-bracket"></i> &nbsp;Sign out</a>
                </div>
            </div>
        {% else %}
        <div>
            <a href="{% url 'userauth:login' %}" class="px-4 py-1 text-lg font-medium bg-[#ef6540] text-white rounded-md hover:bg-[#f07a5d] mr-4">Log in</a>
            
            <a href="{% url 'userauth:signup' %}" class="px-4 py-1 text-lg font-medium border border-[#ef6540] text-[#ef6540] hover:text-white rounded-md hover:bg-[#ef6540]">Sign up</a>
        </div>
        {% endif %}
 
    </nav>
    
    <!-- flash messages -->
    {% if messages %}
        {% for message in messages %}
            <div class="flex items-center p-4 my-4 mx-4 text-sm text-green-800 border border-green-300 rounded-lg bg-green-50 " role="alert" id="flash-message">
                <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                </svg>
                <div>
                    <span class="font-medium">{{ message }}</span>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    <script>
         setTimeout(function () {
            $('#flash-message').fadeOut();
        }, 5000);
    </script>
    
    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer class="pt-6">
        <div class="bg-[#0f2e40] p-4 text-white flex justify-around items-center mb-8">
            <p class="font-semibold text-xl">
                Browse through our products library!
            </p>
            <form action="{% url 'product:search' %}" method="GET get" name="search-bar">   
                <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only">Search</label>
                <div class="relative" id="search-bar">
                    <!-- the name attribute in input tag should be same as query field used variable -->
                    <input type="text" value="{{ query }}" id="default-search" class="block p-2 ps-5 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50" placeholder="Search Category, Products..." style="min-width: 300px;" name="query" required>
                </div>
            </form>
        </div>

        <div class="end mb-8">
            <div>
                <div><h1 class="text-[#ee6846] text-3xl font-semibold">AUCTION</h1></div>
                <div>CONTACT@gmail.com</div>
            </div>

            <div>
                <div class="mb-3"><strong class="text-[#ee6846] text-xl font-semibold">Company<span id="company"></span></strong></div>
            
                <div>
                    <ul class="space-y-1">
                        <li>
                            <a href="{% url 'core:index' %}" class="deco">Home</a>
                        </li>
                        <li>
                            <a href="{% url 'core:contact' %}"  class="deco">Contact Us</a>
                        </li>
                        <li>
                            <a href="{% url 'core:terms' %}" class="deco">Terms & Conditions</a>
                        </li>
                    </ul>
                </div>
            </div>

            <div>
                <div class="mb-3"><strong class="text-[#ee6846] text-xl font-semibold">Online Auction <span id="auction"></span></strong></div>
            
                <div>
                    <ul class="space-y-1">
                        <li>
                            <a href="#" class="deco">Ongoing Auction</a>
                        </li>
                        <li>
                            <a href="#" class="deco">Upcoming Auction</a>
                        </li>
                    </ul>
                </div>
            </div>

            <div>
                <div class="mb-3"> 
                    <strong class="text-[#ee6846] text-xl font-semibold">Subscribe Our Newsettler</strong>
                </div>
                
                <div style="color:white">
                    <div><input class="email py-1 px-2 rounded-xl border mb-2" type="text" placeholder="Your E-mail here..." style="min-width: 250px;"></div>
                    <button class="px-4 py-1 text-sm font-medium bg-[#ef6540] text-white rounded-md hover:bg-[#f07a5d] mr-4">Subscribe</button>
                </div>
            </div>
        </div>

        <div class="bg-gray-100 p-3 text-center text-gray-600">
            <p>&#169; 2024 Auction Inc. All Rights Reserved.</p>
        </div>
    </footer>
</body>

<script>
    var loader = document.getElementById("preloader");
    window.addEventListener("load", function(){
        loader.style.display = "none";
    })
</script>

</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Cart |{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/cart.css' %}" />
<script defer>
    var product_amount = "{{ cart_total_price }}";
    var coupon_discount = "{{ coupon.discount }}";
</script>
<script src="{% static 'js/carts.js' %}" defer></script>
<script src="{% static 'js/coupon.js' %}" defer></script>

<main id="cart-list">
    <div class="mt-8 mb-10 ">
        <h2 class="text-4xl text-[#253D4E] font-bold text-center mb-4">Your Cart</h2>
        <h3 class="text-center"><a href="{% url 'core:index' %}" class="text-gray-500 hover:text-orange-500"><i id="home" class="fa fa-home text-xs"></i> Home</a> / Cart</h3>
    </div>
    
    {% if totalcartitems %}
    <div class="flex mb-5 justify-around">
        <div class="shop-summary">
    
            <h2 class="text-center font-medium mb-5 text-xl">There 
                {% if totalcartitems == 1 %}
                    is
                {% else %}
                    are
                {% endif %} <span class="text-emerald-500">
                    {{ totalcartitems }}</span> 
                {% if totalcartitems == 1 %}
                    Product
                {% else %}
                    Products
                {% endif %} in your cart</h2>
    
            <table class="table-cart w-full text-center p-2">
                <thead class="bg-gray-100 rounded-lg">
                    <tr class="main-heading">
                        <th class="p-3">Image</th>
                        <th class="p-3">Product Title</th>
                        <th class="py-3 px-5">Price</th>
                        <th class="py-3 px-5">Quantity</th>
                        <th class="py-3 px-5">Total</th>
                        <th class="py-3 px-5">Refresh</th>
                        <th class="py-3 px-5">Remove</th>
                    </tr>
                </thead>
    
                <tbody>
                    {% for product_id, item in cart_data.items %}
                        <tr class="border-b">
                            <td id="product-thumbnail" class="image p-3">
                                <img src="{{ item.image }}" alt="#" class="border rounded-lg object-contain">
                            </td>
                            <td>
                                <p id="item-name"><a href="{% url 'product:detail' item.pid %}" class="hover:text-rose-700">{{ item.title|truncatechars:30 }}</a></p>
                            </td>
    
                            <td class="text-emerald-500 pl-4 pr-3 py-3">${{ item.price|floatformat:2 }}</td>
    
                            <td class="px-3 py-3" id="qty">
                                <input type="number" class="p-2 border border-emerald-500 rounded-md product-qty-{{ product_id }}" value="{{ item.qty }}" name="" id="">
                            </td>
    
                            <td class="text-emerald-500 px-3 py-3">${% widthratio item.price 1 item.qty %}</td>
    
                            <td class="px-3 py-3"><button class="update-product" data-product="{{ product_id }}"><i class="fa fa-refresh hover:text-rose-600"></i></button></td>
    
                            <td class="px-3 py-3"><button class="delete-product" data-product="{{ product_id }}"><i class="fa-thin fa-trash hover:text-rose-600"></i></button></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <hr class="my-5">

            <!-- coupon code area -->
            <div>
                {% if invalid_coupon %}
                    <div class="flex items-center p-3 mb-4 text-sm text-yellow-800 border border-yellow-300 rounded-lg bg-yellow-50" role="alert" id="flash-message">
                        <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                        </svg>
                        <div>
                            <span class="font-medium">{{ coupon.code }}</span> {{ invalid_coupon }}
                        </div>
                    </div>
                {% elif valid_coupon %}
                    <div class="flex items-center p-3 mb-4 text-sm text-green-800 border border-green-300 rounded-lg bg-green-50" role="alert" id="flash-message">
                        <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                        </svg>
                        <div>
                            <span class="font-medium">{{ coupon.code }}</span> {{ valid_coupon }}
                        </div>
                    </div>
                {% endif %}
                <form method="get">
                    <input type="text" name="coupon-code" placeholder="Enter Coupon Code..." class="border py-2 px-3 rounded-md">
                    <button class="py-2 px-3 bg-[#253D4E] text-white rounded-md hover:bg-[#252D50] mb-4" type="submit">Apply Coupon</button>
                </form>
            </div>
            
        </div>
        {% else %}
            <p class="text-center flex justify-center">
                <img src="{% static 'assets/empty.png' %}" alt="image" style="height: 300px; width: 300px;">
            </p>
            <h2 class="text-4xl text-center font-bold mb-8">Your Cart is Empty</h2>

            <div class="text-center mb-10 text-lg">
                <p>Add something to the cart</p>
                <p>Start <a href="{% url 'product:shop' %} " class="text-emerald-500 font-medium">shopping</a> to view products in your cart</p>
            </div>
            <div class="text-center p-2 mb-20">
                <a href="{% url 'core:index' %}" class="p-3 bg-emerald-500 rounded-md text-xl text-white hover:bg-emerald-700"><i class="fa-thin fa-home"></i>&nbsp;  Back To Home Page</a>
            </div>
        {% endif %}
    
        {% if totalcartitems %}
        <div>
            <h2 class="text-2xl font-semibold text-center mb-4">Cart Totals</h2>
            <div class="total cart-total-price p-1">
                <div class="my-2 flex justify-between font-medium mx-5">
                    Subtotal
                    <p class="text-emerald-500">${{cart_total_price}}</p>
                </div>
                <div class="mb-2 flex justify-between font-medium mx-5">
                    Items
                    <p>{{totalcartitems}}</p>
                </div>
                {% if valid_coupon %}
                    <div class="mb-2 flex justify-between font-medium mx-5 text-rose-500">
                        Coupon Discount
                        <p>-{{coupon.discount}}%</p>
                    </div>

                <hr>
                {% endif %}
                <div class="my-3 font-semibold flex justify-between mx-5">
                    Total
                    <p class="text-emerald-500" id="total">${{cart_total_price}}</p>
                </div>
            </div>

            <div class="text-center text-white font-medium mt-6">
                <a class="bg-emerald-500 px-5 py-2 rounded-md hover:bg-emerald-700" href="{% url 'product:checkout' %}">Procced to Checkout &nbsp;<i class="fa fa-sign-out"></i></href=></a>
            </div>
        </div>
        {% endif %}
    
    </div>
</main>

{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Contact Us |{% endblock %}

{% block content %}
<script src="{% static 'js/function7.js' %}" defer></script>

<div class="mt-8 mb-10 ">
    <h2 class="text-4xl text-[#253D4E] font-bold text-center mb-4">Contact Us</h2>
    <h3 class="text-center"><a href="{% url 'core:index' %}" class="text-gray-500 hover:text-orange-500"><i id="home" class="fa fa-home text-xs"></i> Home</a> / Contact Us</h3>
</div>
<div class="flex justify-center mb-10">
    <div class="text-center" style="width: 700px;">
        <h2 class="text-4xl mb-2 font-semibold text-[#253D4E]">Leave a Message</h2>
        <p class="text-gray-500 mb-8">Our staff will call back later and answer your questions.</p>
        <h3 id="message-after" class="text-emerald-500 text-3xl font-medium"></h3>
        <form action="" method="POST" id="contact-form">
            {% csrf_token %}
            <div class="flex mb-4">
                <input id="full_name" type="text" class="w-1/2 mr-2 p-3 border rounded-xl" placeholder="Full Name" required>
                <input id="email" type="email" class="w-1/2 ml-2 p-3 border rounded-xl" placeholder="Your Email" required>
            </div>
            <div class="flex mb-4">
                <input id="phone" type="number" class="w-1/2 mr-2 p-3 border rounded-xl" placeholder="Phone no.">
                <input id="subject" type="text" class="w-1/2 ml-2 p-3 border rounded-xl" placeholder="Subject" required>
            </div>
            <textarea placeholder="Your Message" id="message" cols="30" rows="10" class="w-full p-3 border rounded-xl mb-4" required></textarea>
            <button type="submit" class="bg-[#253D4E] text-white py-3 px-8 rounded-xl hover:bg-[#252D50] ">Send Message</button>
        </form>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %}Home |{% endblock %}
{% load static %}


{% block content %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
<link rel="stylesheet" href="{% static 'css/tw-output.css' %}">



<!------------------------------------------------------------------>
<!-------------------------- Auction Section ----------------------->
<!------------------------------------------------------------------>
<div class="mt-6 mb-5 px-6 py-12 bg-[#F4F5F7]">
    <h2 class="mb-12 text-3xl text-center font-semibold underline text-[#0f2e40]">Latest Auctions</h2>
    
    <div class="container gap-2" id="p-section">
        {% for auction in auctions %}
        <div class="card">
            <a href="{% url 'product:auction_detail' auction.id %}" class="detail">
                <div>
                    <img src="{{ auction.image.url }}" class="rounded-t-xl border-1" id="product">
                    <span class="ml-2 bg-rose-600 text-white py-1 px-3 rounded-md" id="auction-live"><i class="far fa-dot-circle"> Live</i></span>
                </div>
                
                <div class="p-6 border-t-2 bg-white w-70 card1">
                    <h3 class="text-xl text-center font-medium mb-2">{{ auction.name }}</h3>
                    <div class="flex">
                        <strong class="text-gray-900">Opening Bid:</strong>
                        <p class="text-gray-700 text-center ml-2"><span id="price">$</span>{{ auction.bid }}</p>
                        <div class="go-arrow">
                            →
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>


<div class="mt-6 px-6 py-12">
    <h2 class="mb-12 text-3xl text-center text-[#0f2e40] font-semibold">Auction Categories</h2>
    <a href="{% url 'product:category' %}" class="underline flex flex-row-reverse text-xl hover:text-rose-600">See all</a>
    <div class="grid grid-cols-5 gap-3">
        {% for category in categories %}
        <div>
            <div class="p-6 bg-white rounded-xl text-center">
                <a href="{% url 'product:auction-list' category.id %}" class="hover:text-rose-600 text-center">
                    <img src="{{ category.image.url }}" class="border rounded-full" id="c-auction">
                    <span class="text-2xl font-medium mt-2">{{ category.name }}</span>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<!------------------------------------------------------------------>
<!-------------------------- Product Section ----------------------->
<!------------------------------------------------------------------>
<div class="mt-10 mb-5 px-6 py-12 bg-[#F4F5F7]">
    <h2 class="mb-12 font-semibold text-3xl text-center underline text-[#0f2e40]">Latest Products</h2>

    <div class="container gap-2" id="p-section">
        {% for p in products %}
            <div class="card">
                <div class="detail">
                    <div>
                        <img src="{{ p.image.url }}" class="rounded-t-xl border-1" id="product">
                        <!-- we are making all hidden input so that function.js can take the value of the product and add to cart from homepage -->
                        <div class="text-center" id="home-cart">
                            <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{ p.id }}">

                            <input type="hidden" value="{{ p.id }}" class="product-pid-{{ p.id }}">

                            <input type="hidden" value="{{ p.image.url }}"
                            class="product-image-{{ p.id }}">

                            <input type="hidden" value="{{ p.id }}" class="product-id-{{ p.id }}">

                            <input type="hidden" value="{{ p.title }}" class="product-title-{{ p.id }}">

                            <button class="add add-to-cart-btn bg-[#ee6846] text-white py-.5 px-3 hover:bg-[#ee5856]" id="add-to-cart-btn" data-index="{{ p.id }}"><i class="fa-regular fa-cart-shopping" ></i></button>
                        </div>
                    </div>

                    <a href="{% url 'product:detail' p.id %}" class="px-5 pt-3 border-t-2 bg-white w-70 card1">
                        <h3 class="text-xl font-medium text-center mb-2">{{ p.title }}</h3>
                        <p class="text-gray-800 font-semibold text-center text-xl"><span id="price">$</span><span class="current-price-{{ p.id }}">{{ p.price }}</span><s class="ml-2 text-sm text-gray-400">${{ p.old_price }}</s></p>
                        <div class="go-arrow">
                            →
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>


<div class="mt-6 px-6 py-12">
    <h2 class="mb-12 text-3xl text-[#0f2e40] text-center font-semibold">Product Categories</h2>
    
    <a href="{% url 'product:category-p' %}" class="underline flex flex-row-reverse text-xl hover:text-rose-600">See all</a>

    <div class="grid grid-cols-5 gap-3">
        {% for category in categories %}
            <div>
                <div class="p-6 bg-white rounded-xl text-center">
                    <a href="{% url 'product:product-list' category.id %}" class="hover:text-rose-600">
                        <img src="{{ category.image.url }}" class=" border rounded-full" id="c-product" alt="Image">
                        <span class="text-2xl font-medium mt-2">{{ category.name }}</span>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}